#include "ui/styles/DarkThemeStyle.h"

QString DarkThemeStyle::styleSheet() const
{
  return
    "QMainWindow { background-color: #1b2635; }"
    "QFrame#objectsPanel, QFrame#renderStatsPanel, QFrame#inspectorPanel, QFrame#viewportPanel {"
    "  background-color: #131925;"
    "  border: 1px solid #243042;"
    "  border-radius: 12px;"
    "}"
    "QLabel#panelTitle { color: #9aa6b2; font-weight: 700; font-size: 18px; }"
    "QScrollArea#inspectorScrollArea { background-color: #131925; border: none; }"
    "QScrollArea#inspectorScrollArea > QWidget > QWidget { background-color: #131925; }"
    "QScrollArea#objectsScrollArea { background-color: #131925; border: none; }"
    "QScrollArea#objectsScrollArea > QWidget > QWidget { background-color: #131925; }"
    "QWidget#inspectorContent { background-color: #131925; }"
    "QListWidget#objectList { background: transparent; color: #d8e1ea; border: none; }"
    "QListWidget#objectList::item { padding: 8px; border-radius: 6px; }"
    "QListWidget#objectList::item:selected { background: #243042; }"
    "QFrame#inspectProviderItem {"
    "  background-color: transparent;"
    "  border: 1px solid transparent;"
    "  border-radius: 8px;"
    "}"
    "QFrame#inspectProviderItem:hover {"
    "  background-color: rgba(154, 166, 178, 0.12);"
    "  border: 1px solid rgba(154, 166, 178, 0.20);"
    "}"
    "QFrame#inspectProviderItem[selected=\"true\"] {"
    "  background-color: rgba(72, 119, 176, 0.32);"
    "  border: 1px solid rgba(126, 166, 207, 0.75);"
    "}"
    "QFrame#inspectProviderItem QLabel { color: #d8e1ea; }"
    "QFrame#inspectProviderItem QToolButton {"
    "  border: none;"
    "  border-radius: 4px;"
    "  padding: 2px;"
    "  background: transparent;"
    "}"
    "QFrame#inspectProviderItem QToolButton:hover {"
    "  background-color: rgba(154, 166, 178, 0.18);"
    "}"
    "QLabel { color: #d8e1ea; }"
    "QLineEdit, QDoubleSpinBox, QComboBox {"
    "  background: #0f1723; color: #d8e1ea; border: 1px solid #243042; border-radius: 6px;"
    "}"
    "QCheckBox { color: #d8e1ea; }";
}
